/**
 * Strategy Event Types
 *
 * @deprecated This module is being phased out. Strategy events are being split into:
 * - PolicySettings (src/types/strategies/unified.ts) - Always-active singleton policies
 * - Regular events (Tax Optimization, Investment categories) - Time-bound automations
 *
 * See the Policy/Strategy unification plan for migration details.
 *
 * This module defines event types for strategies as first-class events.
 * Strategies are duration-based events with start/end dates that can be
 * visualized on the timeline and traced in deterministic simulations.
 */

import { BaseEvent, EventType } from './base';

// =============================================================================
// STRATEGY PHASE - Lifecycle phases for strategy execution
// =============================================================================

/**
 * StrategyPhase represents the current lifecycle phase of a strategy.
 * Used for visualization (color-coding) and filtering.
 */
export type StrategyPhase =
  | 'accumulation'    // Building wealth (contributions, growth)
  | 'conversion'      // Tax conversion phase (Roth conversions)
  | 'withdrawal'      // Decumulation phase (retirement withdrawals)
  | 'rebalancing'     // Active portfolio rebalancing
  | 'maintenance';    // Ongoing maintenance strategies

/**
 * Strategy phase colors for timeline visualization
 */
export const STRATEGY_PHASE_COLORS: Record<StrategyPhase, string> = {
  accumulation: '#10b981',  // emerald-500
  conversion: '#8b5cf6',    // violet-500
  withdrawal: '#f59e0b',    // amber-500
  rebalancing: '#6366f1',   // indigo-500
  maintenance: '#64748b',   // slate-500
};

// =============================================================================
// STRATEGY POLICY EVENT - Duration-based strategy definition
// =============================================================================

export const STRATEGY_POLICY_EVENT_TYPE = EventType.STRATEGY_POLICY;

/**
 * StrategyPolicyEvent - A strategy represented as a duration-based event
 *
 * This event type wraps a strategy configuration and defines when the strategy
 * is active. It enables strategies to be visualized on the timeline and
 * managed alongside other financial events.
 */
export interface StrategyPolicyEvent extends BaseEvent {
  type: typeof STRATEGY_POLICY_EVENT_TYPE;

  /** Strategy identifier linking to strategy definition (e.g., 'asset-allocation') */
  strategyId: string;

  /** Strategy type for discrimination (e.g., 'INVESTMENT', 'TAX_OPTIMIZATION') */
  strategyType: string;

  /** Current phase of strategy execution */
  phase: StrategyPhase;

  /** Month offset when strategy becomes active */
  startDateOffset: number;

  /** Month offset when strategy ends (undefined = ongoing/permanent) */
  endDateOffset?: number;

  /** Strategy configuration snapshot (parameters, settings) */
  configuration: Record<string, any>;

  /** Human-readable policy summary for UI display */
  policySummary: string;

  /** Color for timeline visualization (defaults to phase color) */
  visualizationColor?: string;

  /** IDs of events generated by this strategy (for reference) */
  generatedEventIds?: string[];
}

/**
 * Type guard for StrategyPolicyEvent
 */
export function isStrategyPolicyEvent(event: { type: EventType }): event is StrategyPolicyEvent {
  return event.type === STRATEGY_POLICY_EVENT_TYPE;
}

// =============================================================================
// STRATEGY EXECUTION EVENT - Individual strategy action
// =============================================================================

export const STRATEGY_EXECUTION_EVENT_TYPE = EventType.STRATEGY_EXECUTION;

/**
 * StrategyTransaction - A single financial operation within a strategy execution
 */
export interface StrategyTransaction {
  /** Unique identifier */
  id: string;

  /** Human-readable description (e.g., "$50,000 from 401k → Taxable") */
  description: string;

  /** Source account type for transfers/withdrawals */
  sourceAccount?: string;

  /** Target account type for contributions/deposits */
  targetAccount?: string;

  /** Transaction amount */
  amount: number;

  /** Type of transaction */
  transactionType: 'transfer' | 'contribution' | 'withdrawal' | 'conversion' | 'rebalance' | 'trade';

  /** Tax impact of this transaction (positive = tax owed) */
  taxImpact?: number;

  /** Capital gain/loss from this transaction */
  capitalGainLoss?: number;
}

/**
 * StrategyExecutionEvent - An individual strategy action with transaction details
 *
 * This event captures when a strategy actually executes (e.g., performs a rebalance,
 * makes a withdrawal). It includes detailed transaction information for tracing.
 */
export interface StrategyExecutionEvent extends BaseEvent {
  type: typeof STRATEGY_EXECUTION_EVENT_TYPE;

  /** Strategy identifier this execution belongs to */
  strategyId: string;

  /** Strategy name for display */
  strategyName: string;

  /** Phase during which this execution occurred */
  phase: StrategyPhase;

  /** Detailed transaction breakdown */
  transactions: StrategyTransaction[];

  /** Reason for this specific execution */
  executionReason: string;

  /** Execution type for filtering (e.g., 'rebalance', 'withdrawal', 'conversion') */
  executionType: 'rebalance' | 'withdrawal' | 'conversion' | 'contribution' | 'tax_harvest' | 'other';

  /** Total amount involved in this execution */
  totalAmount?: number;

  /** Total tax impact of all transactions */
  totalTaxImpact?: number;
}

/**
 * Type guard for StrategyExecutionEvent
 */
export function isStrategyExecutionEvent(event: { type: EventType }): event is StrategyExecutionEvent {
  return event.type === STRATEGY_EXECUTION_EVENT_TYPE;
}

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Get the visualization color for a strategy phase
 */
export function getStrategyPhaseColor(phase: StrategyPhase): string {
  return STRATEGY_PHASE_COLORS[phase] || STRATEGY_PHASE_COLORS.maintenance;
}

/**
 * Get a human-readable label for a strategy phase
 */
export function getStrategyPhaseLabel(phase: StrategyPhase): string {
  const labels: Record<StrategyPhase, string> = {
    accumulation: 'Accumulation',
    conversion: 'Conversion',
    withdrawal: 'Withdrawal',
    rebalancing: 'Rebalancing',
    maintenance: 'Maintenance',
  };
  return labels[phase] || 'Unknown';
}

/**
 * Determine strategy phase based on strategy type and configuration
 */
export function determineStrategyPhase(strategyId: string, config?: Record<string, any>): StrategyPhase {
  // Map strategy IDs to their primary phases
  const phaseMap: Record<string, StrategyPhase> = {
    'investment-optimization': 'rebalancing',
    'asset-allocation': 'rebalancing',
    'retirement-withdrawal': 'withdrawal',
    'roth-conversion': 'conversion',
    'tax-loss-harvesting': 'maintenance',
    'tax-withholding': 'maintenance',
    'contribution-optimization': 'accumulation',
    'social-security-optimization': 'withdrawal',
  };

  return phaseMap[strategyId] || 'maintenance';
}
